server:
  port: 8000

spring:
  application:
    name: BurgerkingCloneCoding
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB

  datasource:
    url: jdbc:mariadb://dev.macacolabs.site:8008/burgerking
    username: burgerking
    password: burgerking
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

s3:
  endpoint: http://dev.macacolabs.site:9000
  access-key: WU04kde1FqpJAVR9exaV
  secret-key: 1ZNUJ3OzqfZsNWMhhMjgyZej0BH9fKVbQSwX1EiN
  bucket: burgerking
  region: ap-northeast-2